name: Build master

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup environment
        if: ${{ !env.ACT }}
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Start ganache and test solution
        run: yarn ganache:start & yarn test
        env:
          CI: true
